[Camera]
; Restrict min zoom to ensure gamepad and mouse have the same experience.
; Increments of 0.075 are equivalent to 40 units.
fMinCurrentZoom=0              ; default=-0.2
fMouseWheelZoomIncrement=0.075 ; default=0.075

; Setting below 0.25 makes 3rd person use minimum zoom after switching.
f1st3rdSwitchDelay=0           ; default=0.25

; Auto vanity fly cam - start faster, zoom closer, and spin slower.
fAutoVanityModeDelay=90        ; default=120
fDefaultAutoVanityZoom=200     ; default=300
fAutoVanityIncrement=0.0025    ; default=0.01

[Controls]
; Allow more camera rotation during dialogue.
fDialogueHardStopAngle3P=150   ; default=55
fDialogueSoftStopAngle3P=135   ; default=25