## --
## for a detailed guide, visit the BTPS wiki on GitLab (linked on Nexus page)
##
## also, take a look at FilterPresets_Default.toml - both files work identically - only edit FilterPresets.toml, not FilterPresets_Default.toml
## --